Moved all documentation uploading to the Documentation Makefile, fixing its packaging and installation

diff --git a/MusicKit/Documentation/Makefile.in b/MusicKit/Documentation/Makefile.in
--- a/MusicKit/Documentation/Makefile.in
+++ b/MusicKit/Documentation/Makefile.in
@@ -34,7 +34,8 @@ OBJDIR=/tmp
 VERSION=0.0.0
 
 BUILDDIR=$(OBJDIR)/MKDocumentation.build
-DOC_TARBALL=$(BUILDDIR)/MusicKitREADME.tar.bz2
+DOC_TARBALL_FILE=MusicKitREADME.tar.bz2
+DOC_TARBALL_PATH=$(BUILDDIR)/$(DOC_TARBALL_FILE)
 
 # We allow the path to the ChangeLog to be passed in on the command
 # line since it is generated in the source packaging process.
@@ -44,6 +45,11 @@ CHANGELOG=
 HTML_DISTRIB_DIR=htdocs
 HTML_TMPDIR=$(BUILDDIR)/$(HTML_DISTRIB_DIR)
 PDF_OUTPUT_DIR=$(BUILDDIR)/PDF
+
+SITEUSER=leighsmith
+SITE=musickit.sourceforge.net
+SITEDIR=/home/groups/m/mu/musickit
+SITEHTMLDIR=$(SITEDIR)/$(HTML_DISTRIB_DIR)
 
 MK_STYLEDIR=SGML
 MK_STYLESHEET=$(MK_STYLEDIR)/MusicKit_README.dsssl
@@ -68,23 +74,36 @@ HTMLS=$(addprefix $(HTML_TMPDIR)/, index.html \
 #
 ADMONIMAGESDIR=/sw/share/sgml/dsssl/docbook-dsssl-nwalsh/images
 
-INSTALL_DIR=$(DSTROOT)/Library/Documentation
+#
+# Where documentation is installed on a local system.
+#
+INSTALL_DIR=$(DSTROOT)/Library/Documentation/MusicKit
 
-# Generate the HTML tarball. The HTML tarball will create the PDF
+# 
+# The highest level and default rule, make everything.
+# Generates the HTML tarball. The HTML tarball will create the PDF
 # before it copies them into the HTML directory.
-all: check_sgmltrans $(DOC_TARBALL)
-
-check_sgmltrans:
-	if [ $(SGMLTRANS)_x = _x ]; then echo "DocBook SGML translator not found"; exit 1; fi
+#
+all: check_sgmltrans $(DOC_TARBALL_PATH)
 
 clean:
 	-rm -rf $(HTML_TMPDIR)
 	-rm -rf $(PDF_OUTPUT_DIR) 
 
-install:: $(DOC_TARBALL) $(INSTALL_DIR)
-	(cd $(INSTALL_DIR); tar xjfp $(DOC_TARBALL); mv htdocs MusicKit )
+install:: $(DOC_TARBALL_PATH) $(INSTALL_DIR)
+	tar -x -j -C $(INSTALL_DIR) -p -f $(DOC_TARBALL_PATH)
 	-chmod -R go-w $(INSTALL_DIR)
 	-chmod -R ugo+r $(INSTALL_DIR)
+
+#
+# Automate the secure uploading of the MusicKit documentation tarball to the sourceforge website.
+#
+upload: $(DOC_TARBALL_PATH)
+	scp $(DOC_TARBALL_PATH) $(SITEUSER)@$(SITE):$(DOC_TARBALL_FILE)
+	ssh -l $(SITEUSER) $(SITE) "tar -x -j -C $(SITEHTMLDIR) -f ~/$(DOC_TARBALL_FILE)"
+
+check_sgmltrans:
+	if [ $(SGMLTRANS)_x = _x ]; then echo "DocBook SGML translator not found"; exit 1; fi
 
 $(INSTALL_DIR):
 	mkdir -p $(INSTALL_DIR)
@@ -189,7 +208,7 @@ $(HTML_TMPDIR)/Frameworks/index.html: $(DOXYCSS)
 #
 # Create a tarball.
 #
-$(DOC_TARBALL): $(PDFS) $(HTMLS) Publications/*.pdf $(CHANGELOG)
+$(DOC_TARBALL_PATH): $(PDFS) $(HTMLS) Publications/*.pdf $(CHANGELOG)
 	# Copy all PDFs to be placed on the web-site, 
 	mkdir -p $(HTML_TMPDIR)/Publications
 	# those prepared beforehand... 
@@ -198,5 +217,5 @@ $(DOC_TARBALL): $(PDFS) $(HTMLS) Publications/*.pdf $(CHANGELOG)
 	-if [ $(CHANGELOG)_x != _x ]; then cp $(CHANGELOG) $(HTML_TMPDIR); fi
 	# and those generated by this script.
 	cp $(PDFS) $(HTML_TMPDIR)
-	cd $(HTML_TMPDIR)/..; tar cjf $(DOC_TARBALL) $(HTML_DISTRIB_DIR)
+	tar -c -j -C $(HTML_TMPDIR) -f $(DOC_TARBALL_PATH) .
 	# echo $(basename $(HTML_TMPDIR))
